import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ToastContainer } from 'react-toastify';
import { Poppins } from 'next/font/google';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import './globals.css';

const Gotham = localFont({
  src: [
    {
      path: '../fonts/Gotham-Book.otf',
      weight: '400',
      style: 'book',
    },
    {
      path: '../fonts/Gotham-Medium.otf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../fonts/Gotham-Thin.otf',
      weight: '100',
      style: 'thin',
    },
    {
      path: '../fonts/Gotham-Bold.otf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../fonts/Gotham-Light.otf',
      weight: '300',
      style: 'light',
    },
  ],
  variable: '--font-gotham',
  preload: true,
});

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poppins',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Gazi Home Appliance',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Gotham.variable} ${poppins.variable}`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
